'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class TypeIDs
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("VB_EVE_Character_Tracker.TypeIDs", GetType(TypeIDs).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0,#System
        '''2,Corporation
        '''3,Region
        '''4,Constellation
        '''5,Solar System
        '''6,Sun G5 (Yellow)
        '''7,Sun K7 (Orange)
        '''8,Sun K5 (Red Giant)
        '''9,Sun B0 (Blue)
        '''10,Sun F0 (White)
        '''11,Planet (Temperate)
        '''12,Planet (Ice)
        '''13,Planet (Gas)
        '''14,Moon
        '''15,Asteroid Belt
        '''16,Stargate (Caldari System)
        '''17,Stargate (Amarr Constellation)
        '''18,Plagioclase
        '''19,Spodumain
        '''20,Kernite
        '''21,Hedbergite
        '''22,Arkonor
        '''23,Cargo Container
        '''24,Ring
        '''25,Corpse
        '''26,Office Folder
        '''27,Office
        '''28,Factory Folder
        '''29,Credits
        '''30,Faction
        '''34,Tritanium
        '''35, [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Kronos_98534_typeID() As String
            Get
                Return ResourceManager.GetString("Kronos_98534_typeID", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
